[build-system]
requires = ["setuptools>=77.0.3"]
build-backend = "setuptools.build_meta"

[project]
name = "docsync-ai"
version = "0.0.1"
description = "A tool for generating and synchronizing documentation with code changes."
authors = [
    {name = "Daniel Angelov"},
]
license = "MIT"
license-files = ["LICENSE"]
requires-python = ">=3.11"
readme = "README.md"

[project.optional-dependencies]
dev = [
  "pytest>=8.0,<10.0",
  "ruff>=0.13,<1.0",
]

[tool.setuptools.packages.find]
where = ["src"]
include = ["docsync*"]